### ISSUE TITLE
Map product instance to version of product properties

### ISSUE THREAD

**Issue by Toxantron** [PHOENIXCONTACT/MORYX-AbstractionLayer#2]
Currently we only reference the revision as type of the product instance, but not the exact version of the properties used to create the instance.

**Comment by 1nf0rmagician** [comment]
We restrict the feature to the current status, as an alternative revisions can be used for products

**Comment by dbeuchler** [comment]
@1nf0rmagician I think you have not got the problem itself. It is currently not possible to get the `ProductProperties` from an `ProductInstance`. This destroys the complete traceability of instances because you never get the real ProductType-data to the instance. Revisions cannot be used because the revision stays stable and is required (for printing, ...) even if properties of the products are changed. 

There comes another point in my mind: It is never possible to restore a product instance from the storage with the "old" product type properties. 

1. Produce product type and abort
2. Change product type without changing revision
3. Reload instance 

Instance will get type information of the new version instead of the "old". At the end it is not an `enhancement` it is a `bug` which gets visible if instances are reloaded and the old information is required.

My proposal is: repopen it and find a smart way to store the product properties reference on the instance.
